In [4]:
import numpy as np
# NumPy 패키지를 임포트


In [5]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x
#1차원 배열 만들기, array함수에 리스트를 넣으면 배열로 변환

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
type(x)
# 타입확인

numpy.ndarray

In [7]:
2 * x
# 2배 한 경우

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [9]:
2 * a + b

array([12, 24, 36])

In [10]:
a == 2

array([False,  True, False])

In [11]:
b > 10

array([False,  True,  True])